### ISSUE TITLE
ApptrackingService NullPointerException

### ISSUE THREAD

**Issue by leonpoint** [FHellmann/Uniatron#62]
function blockByLearningAid throws NullPointerException

07-01 23:44:26.223 10066-10066/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.edu.uni.augsburg.uniatron, PID: 10066
    java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
        at com.edu.uni.augsburg.uniatron.service.AppTrackingService.blockByLearningAid(AppTrackingService.java:225)
        at com.edu.uni.augsburg.uniatron.service.AppTrackingService.delegateAppUsage(AppTrackingService.java:184)

**Comment by FHellmann** [comment]
Outdated to the master branch
